key = 053867d6-8f46-4309-b7ad-e5656c3a2364
region = EUW	

# Check: https://developer.riotgames.com/docs/regional-endpoints 
glboal_endpoint = https://global.api.pvp.net
regional_endpoint = https://euw.api.pvp.net

seed=666

attacker.champion=Gangplank
attacker.level=3
attacker.skills=2*Parrrley
attacker.items=1*BrawlersGloves
attacker.runes=9*Mark*criticalBonusDamage+9*Seal*criticalBonusDamage+9*Glyph*criticalBonusDamage+3*Quintessence*criticalBonusDamage

defender.champion=Caitlyn
defender.level=3