seed=666

attacker.champion=Gangplank
attacker.level=3
attacker.skills=2*Parrrley
attacker.items=1*BrawlersGloves
attacker.runes=9*Mark*criticalBonusDamage+9*Seal*criticalBonusDamage+9*Glyph*criticalBonusDamage+3*Quintessence*criticalBonusDamage

defender.champion=Caitlyn
defender.level=3