key = 053867d6-8f46-4309-b7ad-e5656c3a2364
region = euw	

# Check: https://developer.riotgames.com/docs/regional-endpoints 
glboal_endpoint = https://global.api.pvp.net
regional_endpoint = https://euw.api.pvp.net