abilityPower.Mark=0.59
abilityPower.Seal=0.59
abilityPower.Glyph=0.59
abilityPower.Quintessence=0.59

abilityPowerPerLevel.Mark=0.1
abilityPowerPerLevel.Seal=0.1
abilityPowerPerLevel.Glyph=0.17
abilityPowerPerLevel.Quintessence=0.43

attackDamage.Mark=0.95
attackDamage.Seal=0.43
attackDamage.Glyph=0.28
attackDamage.Quintessence=2.25

attackDamagePerLevel.Mark=0.13
attackDamagePerLevel.Seal=0.06
attackDamagePerLevel.Glyph=0.04
attackDamagePerLevel.Quintessence=0.25

criticalChance.Mark=0.93
criticalChance.Seal=0.42
criticalChance.Glyph=0.28
criticalChance.Quintessence=1.86

criticalBonusDamage.Mark=2.23
criticalBonusDamage.Seal=0.78
criticalBonusDamage.Glyph=0.56
criticalBonusDamage.Quintessence=4.46

armorPenetration.Mark=1.28
armorPenetration.Seal=
armorPenetration.Glyph=
armorPenetration.Quintessence=2.56
